Repository lablup/backend.ai-common, pull requests merged in 2021-12, with the labels that each got.

#100 Removed unreachable statement
  changes/100.fix
  src/ai/backend/common/types.py
Labels: refactor

#99 feat: Update TimeDuration to support years and months
  changes/99.feature
  src/ai/backend/common/validators.py
  tests/test_validators.py
Labels: feature

#104 fix: Apply mypy 0.920 update
  changes/104.fix
  setup.cfg
  src/ai/backend/common/cli.py
  src/ai/backend/common/types.py
Labels: maintenance

#105 Update mypy to 0.930
  changes/105.fix
  setup.cfg
  src/ai/backend/common/etcd.py
  src/ai/backend/common/utils.py
  tests/test_utils.py
Labels: maintenance
