Repository lablup/backend.ai-common, pull requests merged in 2022-05, with the labels that each got.

#141 fix: mypy failing on lock/etcd
  changes/141.fix
  src/ai/backend/common/etcd.py
  src/ai/backend/common/lock.py
  src/ai/backend/common/logging.py
Labels: refactor

#139 fix: Add error logs to notify ConnectionError caused by incorrect redis url
  changes/139.fix
  src/ai/backend/common/redis.py
Labels: bug, maintenance

#142 dep: bump etcetra version
  changes/142.misc
  setup.cfg
Labels: maintenance
