Repository lablup/backend.ai-common, pull requests merged in 2022-03, with the labels that each got.

#119 feat: add architecture alias mapping for docker registry API
  changes/119.feature
  src/ai/backend/common/docker.py
Labels: feature

#122 feat: Add more fields to VFolderMount
  changes/122.feature.md
  src/ai/backend/common/types.py
Labels: feature

#123 setup: Set the minimum required Python version to 3.10
  .github/workflows/default.yml
  .github/workflows/timeline-check.yml
  changes/123.breaking.md
  setup.cfg
  src/ai/backend/common/argparse.py
  src/ai/backend/common/etcd.py
  src/ai/backend/common/validators.py
Labels: maintenance

#124 feat: replace aetcd3 with `etcetra`
  changes/124.feature
  requirements/lint.txt
  requirements/test.txt
  requirements/typecheck.txt
  setup.cfg
  src/ai/backend/common/docker.py
  src/ai/backend/common/etcd.py
  src/ai/backend/common/etcd_beta.py
  src/ai/backend/common/events.py
  src/ai/backend/common/plugin/__init__.py
  tests/conftest.py
  tests/test_etcd.py
  tests/test_plugin.py
Labels: feature

#126 fix: Argument typing of `redis.execute_script()`
  changes/126.fix.md
  src/ai/backend/common/redis.py
Labels: bug

#125 feat: Accept async pipeline builders in `redis.execute()`
  changes/125.feature.md
  src/ai/backend/common/redis.py
  tests/redis/docker.py
  tests/redis/test_pipeline.py
Labels: feature

#128 feat: Accept numbers as well in validators.TimeDuration
  changes/128.feature.md
  src/ai/backend/common/validators.py
  tests/test_validators.py
Labels: feature
