Repository lablup/backend.ai-common, pull requests merged in 2022-04, with the labels that each got.

#130 ci: Run some tests only when related files are changed
  .github/workflows/default.yml
  changes/130.misc.md
  scripts/configure-test.py
  tests/conftest.py
  tests/redis/test_connect.py
  tests/redis/test_list.py
  tests/redis/test_pipeline.py
  tests/redis/test_pubsub.py
  tests/redis/test_stream.py
Labels: maintenance

#129 refactor: Migrate `distributed` module to common pkg
  changes/129.feature.md
  src/ai/backend/common/distributed.py
  src/ai/backend/common/lock.py
  tests/test_distributed.py
Labels: refactor

#131 feat: Allow custom streaming key in EventDispatcher and EventProducer
  changes/131.feature.md
  src/ai/backend/common/events.py
Labels: feature

#127 refactor: remove unused codes in `ImageRef` class
  changes/127.misc
  src/ai/backend/common/docker.py
  tests/test_docker.py
Labels: maintenance

#133 feat: implement Etcd lock
  changes/133.feature
  setup.cfg
  src/ai/backend/common/lock.py
  tests/test_distributed.py
Labels: feature

#132 Prevent deadlock of FileLock
  changes/132.fix.md
  setup.cfg
  src/ai/backend/common/lock.py
Labels: refactor

#135 Migrate bgtask framework to common
  changes/135.fix.md
  setup.cfg
  src/ai/backend/common/bgtask.py
Labels: refactor

#136 Add lifetime to the distributed locks
  changes/136.feature.md
  setup.cfg
  src/ai/backend/common/distributed.py
  src/ai/backend/common/lock.py
  src/ai/backend/common/redis.py
Labels: feature

#138 misc: print warning log when timeout fired on globaltimer
  changes/138.misc
  src/ai/backend/common/distributed.py
  src/ai/backend/common/lock.py
Labels: feature
